### ISSUE TITLE
pushd instead of cd

### ISSUE THREAD

**Issue by Craftidore** [madx/bm#5]
Would be nice if this defaulted (or at least had the option) to use `pushd` instead of `cd`, for easily navigating back to your previous directory.

**Comment by madx** [comment]
This would be nice indeed!
I'm not a big `pushd` user, I mostly only use `cd -`, but I will happily accept a PR for this if it comes as an option.

**Comment by Craftidore** [comment]
I had completely forgotten that the use of `cd` came from the `.inputrc` example, and not from bm at all. Anyway, added a pushd to the README.
